/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda_online;

import com.barcodelib.barcode.QRCode;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author vdgp_
 */
public class carritoComprador extends javax.swing.JPanel {

    String nombre=null;
    FileUsuario fileUsuario=null;
    ArrayList<Producto> carrito=null;
    int total=0;
    //Variables de codigo qr***********************************************************
    int udm=0, resol=72,rot=0;
    float mi=0.000f,md=0.000f,ms=0.000f, min=0.000f, tam=5.00f;
   //********************************************************************************** 
    public carritoComprador(String nombre_) throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        nombre=nombre_;
        fileUsuario=new FileUsuario();
        jLabel2.setText(nombre);
        this.setSize(getPreferredSize());
        fileUsuario.obtenerDatos();
        carrito=fileUsuario.obtenerCarrito(nombre);
        if(carrito.size()==0){
            jButton2.setEnabled(false);
        }
        panel2 p2 = new panel2();
        for(int i=0;i<carrito.size();i++){
            p2.add(new productosCarrito(carrito.get(i),nombre));
            p2.validate();
        }
        scrollPane1.add(p2);
        for(Producto n: carrito){
            int subtotal=Integer.parseInt(n.getPrecio())*Integer.parseInt(n.getCantidad())+Integer.parseInt(n.getCostoEnvio());
        total=total+subtotal;
        }
        jLabel4.setText(Integer.toString(total));
    }
    void generarQr(String info) throws Exception{
        QRCode c = new QRCode();
        c.setData(info);
        c.setDataMode(QRCode.MODE_BYTE);
        c.setUOM(udm);
        c.setLeftMargin(mi);
        c.setRightMargin(md);
        c.setTopMargin(ms);
        c.setBottomMargin(min);
        c.setResolution(resol);
        c.setRotate(rot);
        c.setModuleSize(tam);
        String archivo=System.getProperty("user.home")+"/qrPago.gif";
        c.renderBarcode(archivo);
        Desktop d=  Desktop.getDesktop();
        d.open(new File(archivo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 830));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel2);
        jLabel2.setBounds(290, 60, 135, 36);

        jButton1.setBackground(java.awt.Color.orange);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(760, 60, 150, 41);

        scrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        add(scrollPane1);
        scrollPane1.setBounds(10, 180, 647, 381);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Total: ");
        add(jLabel3);
        jLabel3.setBounds(678, 180, 52, 43);
        add(jLabel4);
        jLabel4.setBounds(748, 180, 119, 43);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagar.png"))); // NOI18N
        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(727, 382, 130, 56);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(340, 20, 32, 35);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(0, 0, 1000, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoblanco.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 130, 980, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Boton regresar
            carritoComprador.this.setVisible(false);
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
            Ventana_Comprador ventanaComprador = new Ventana_Comprador(nombre);
            ventanaComprador.setVisible(true);
            ventanaComprador.setLocationRelativeTo(null);
            ventanaComprador.show();
        } catch (IOException ex) {
            Logger.getLogger(carritoComprador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(carritoComprador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Throwable ex) {
            Logger.getLogger(carritoComprador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton Pagar
        String info="Usuario:"+nombre+"\n"+"Cantidad:"+carrito.size()+"\n"+"Total: "+total; 
        try {
            generarQr(info);
        } catch (Exception ex) {
            Logger.getLogger(carritoComprador.class.getName()).log(Level.SEVERE, null, ex);
        }
        total=0;
        carrito=fileUsuario.obtenerCarrito(nombre);
        scrollPane1.removeAll();
        if(carrito.size()==0){
            jButton2.setEnabled(false);
        }
        for(Producto n: carrito){
            int subtotal=Integer.parseInt(n.getPrecio())*Integer.parseInt(n.getCantidad())+Integer.parseInt(n.getCostoEnvio());
        total=total+subtotal;
        }
        jLabel4.setText(Integer.toString(total));
        fileUsuario.eliminarTodoElCarrito(nombre);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
