/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda_online;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author vdgp_
 */
public class productosCarrito extends javax.swing.JPanel {

   FileUsuario fileUsuario=null;
   String nombre=null;
   Producto producto=null;
   FileProducto fileProducto=null;
    public productosCarrito(Producto Producto_,String nombre_) throws IOException, FileNotFoundException, ClassNotFoundException  {
        initComponents();
        this.setVisible(true);
        producto=Producto_;
        nombre=nombre_;
        fileUsuario=new FileUsuario();
        fileUsuario.obtenerDatos();
         jLabel8.setText(producto.getNombre());
        jLabel9.setText(producto.getNombreVendedor());
        jLabel10.setText(producto.getPais());
        jLabel11.setText(producto.getPrecio());
        jLabel12.setText(producto.getCostoEnvio());
        jLabel13.setText(producto.getDescripcion());
        jLabel15.setText(producto.getCantidad());
        ImageIcon imagen=new ImageIcon(getClass().getResource("/Imagenes/"+producto.getID()+".jpg"));
        Image img=imagen.getImage().getScaledInstance(172, 174, 10);
        jLabel1.setIcon(new ImageIcon(img));
        
        
        fileProducto=new FileProducto();
        fileProducto.obtenerDatos();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(601, 214));
        setLayout(null);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 173, 202);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nombre: ");
        add(jLabel2);
        jLabel2.setBounds(191, 13, 58, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Vendedor:");
        add(jLabel3);
        jLabel3.setBounds(191, 42, 71, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Pais:");
        add(jLabel4);
        jLabel4.setBounds(191, 67, 71, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Precio: ");
        add(jLabel5);
        jLabel5.setBounds(191, 105, 53, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Costo envio:");
        add(jLabel6);
        jLabel6.setBounds(191, 139, 100, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Descripción:");
        add(jLabel7);
        jLabel7.setBounds(191, 173, 90, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel8);
        jLabel8.setBounds(289, 13, 140, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel9);
        jLabel9.setBounds(280, 42, 142, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel10);
        jLabel10.setBounds(280, 67, 142, 16);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel11);
        jLabel11.setBounds(300, 101, 122, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel12);
        jLabel12.setBounds(280, 139, 142, 16);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel13);
        jLabel13.setBounds(280, 173, 142, 16);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(500, 66, 80, 55);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Cantidad");
        add(jLabel14);
        jLabel14.setBounds(440, 175, 57, 16);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(508, 175, 61, 16);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_sesion.png"))); // NOI18N
        add(jLabel17);
        jLabel17.setBounds(0, 200, 750, 10);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoblanco.png"))); // NOI18N
        add(jLabel16);
        jLabel16.setBounds(0, 0, 690, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton borrar
        fileProducto.sumarCantidad(producto.getID(), Integer.parseInt(producto.getCantidad()));
        fileUsuario.eliminarCarrito(nombre,producto);
        //fileProducto.sumarCantidad(producto.getID(), Integer.parseInt(producto.getCantidad()));
        //this.updateUI();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
